### PR TITLE
[gosrc2cpg] - LHS typefullname set with RHS typeFullName fix for #3614

### LINKED ISSUE #3614: [GO] - Type Identification at the time of AST Creation

### PR DESCRIPTION
**Pull request by pandurangpatil**
1. LHS typeFullName set with RHS typeFullName handling covering bothe the declration styles.
2. Boolean LITERAL handling required different way of handling. Made respective changes along with corresponding unit tests.
3. Changed Array Initialiser to take array elements as its argument nodes. Which was not done earlier. Made respective changes in all unit tests.

Fixes #3614

TODO: Add more unit tests and handle Struct type member typeFullName handling along with its cache

### CODE REVIEW

File: joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala [hunk 1]
```diff
@@ -34,47 +38,73 @@ trait AstForExpressionCreator(implicit withSchemaValidation: ValidationMode) { t
...
       .flatMap(_.root)
       .map(_.properties.get(PropertyNames.TYPE_FULL_NAME).get.toString)
       .getOrElse(Defines.anyTypeName)
-    val cNode = createCallNodeForOperator(starExpr, Operators.indirection, typeFullName = Some(typeFullName))
-    Seq(callAst(cNode, operand))
   }
 
   private def astForUnaryExpr(unaryExpr: ParserNodeInfo): Seq[Ast] = {
+    val operand      = astForNode(unaryExpr.json(ParserKeys.X))
+    var typeFullName = getTypeFullNameFromAstNode(operand)
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala:91]: Not the biggest fan of using `var`/mutable variables in this way

**Review by DavidBakerEffendi — APPROVED** [review]
Just left one comment, let me know if I should wait before merging
