### PR TITLE
[c#] Fix RHS of EqualsValueClause

### LINKED ISSUE #4078: [Bug] [c#] Simple Aliased DataFlows Not Working
**Describe the bug**
Trying out a simple dataflow test in the C# frontend. Add a dataflow test with the code below to reproduce. 

```
int i = 0;
int a = i + 1;
Console.WriteLine(a);
```

For the query, 
```
val src  = cpg.identifier.nameExact("i").l
val sink = cpg.call.nameExact("WriteLine").l
```
The expected output for `sink.reachableBy(src).size` should be `2`, but is `0` in this case.

### PR DESCRIPTION
**Pull request by DavidBakerEffendi**
Simple data-flows were not being propagated after some re-assignment. This was found to be caused by only a limited class of RHS nodes being handled on the EqualsValueClause. This has now been fixed and tested.

Other style-related changes added.

Resolves #4078

### CODE REVIEW

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+        |int i = 0;
+        |int a = i + 1;
+        |Console.WriteLine(a);
+        |""".stripMargin))
+
+    "still propagate to the sink" in {
+      cpg.method("Main").dotAst.foreach(println)
+      val src  = cpg.assignment.target.isIdentifier.nameExact("i").l
+      val sink = cpg.call.nameExact("WriteLine").l
+      sink.reachableBy(src).p.foreach(println)
```
Comment (karan-batavia) [inline joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala:21]: Is this a debug statement? We might want to remove this.

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+  "a source with a simple re-assignment" should {
+
+    val cpg = code(basicBoilerplate("""
+        |int i = 0;
+        |int a = i + 1;
+        |Console.WriteLine(a);
+        |""".stripMargin))
+
+    "still propagate to the sink" in {
+      cpg.method("Main").dotAst.foreach(println)
```
Comment (karan-batavia) [inline joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala:18]: Same for this. Also, this test does not assert anything; is this deliberate?

**Review by karan-batavia — APPROVED** [review]
Some questions, LGTM otherwise.

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala (hunk 1 above)
Comment (DavidBakerEffendi) [reply joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/SimpleDataflowTests.scala:21]: Ah yes good catch

**Comment by DavidBakerEffendi** [comment]
@karan-batavia Fixed the test assertions, forgot to assert and remove debugging

**Review by max-leuthaeuser — APPROVED** [review]
