### PR TITLE
[C#] Handle some missing AST Structures, and global classes

### LINKED ISSUE #4153: [C#] Handle AstCreation for `PropertyDeclaration`
Commonly members are declared using a Property Declaration syntax in C#. Ast Nodes should be created for those syntax nodes.
https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/how-to-declare-and-use-read-write-properties

### LINKED ISSUE #4154: [C#] Ast Creation for `FileScopedNamespaceDeclaration`
There is a common pattern in C# where a namespace is declared at the top of a file, and all the types are scoped in that namespace.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

### LINKED ISSUE #4155: [C#] Handle AstCreation for `AwaitExpression`
Call nodes for calls following the `await` statement were not created, so we'll need a Ast Structure for `await` as well.
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await

### LINKED ISSUE #4156: [Bug] [C#] `methodFullName` for `this.call()` not resolved correctly.
When methods are invoked using `this.methodName()`, the `typeFullName` for this, and consequently the methodFullName for the `callNode` are incorrect.

### PR DESCRIPTION
**Pull request by karan-batavia**
This PR includes, 
1. Handle `FileScopedNamespaceDeclaration`
2. Handle `AwaitExpression`
3. Handle `PropertyDeclaration`
2. Type resolution for calls with `this` as the receiver.
4. TypeMap changes to support `global` classes.
5. Dataflow and Ast Creation tests for the above.

Resolves #4153
Resolves #4154
Resolves #4155
Resolves #4156

### CODE REVIEW

**Review by tuxology — APPROVED** [review]
LGTM

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MethodsAndCallDataflowsTests.scala [hunk 1]
```diff
@@ -89,4 +89,70 @@ class MethodsAndCallDataflowsTests extends CSharpCode2CpgFixture(withDataFlow =
...
+        | public int qux(int pQux, string ppQux) {
+        |   return pQux;
+        | }
+        |}
+        |""".stripMargin,
+      fileName = "Baz.cs"
+    )
+
+    "find a path from 1 to res (case 2)" in {
+      val src  = cpg.literal.codeExact("1").l
```
Comment (tuxology) [inline joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MethodsAndCallDataflowsTests.scala:121]: This could use the `inside()` pattern, but not sure what we decided on finally.

Comment (karan-batavia) [reply joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/dataflow/MethodsAndCallDataflowsTests.scala:121]: We don't write dataflow tests using `inside()`

File: joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala [hunk 2]
```diff
@@ -92,16 +94,40 @@ class TypeMap(astGenResult: AstGenRunnerResult, initialMappings: List[NamespaceT
...
-          case NamespaceDeclaration => true
-          case _                    => false
+          case NamespaceDeclaration | FileScopedNamespaceDeclaration | ClassDeclaration => true
+          case _                                                                        => false
+      }
+      .foreach { parserNode =>
+        parserNode.node match
+          case NamespaceDeclaration | FileScopedNamespaceDeclaration => {
+            val (namespace, typesInNamespace) = parseNamespace(parserNode)
+            if (namespaceTypeMap.contains(namespace)) {
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala:110]: Instead of this if-branch, we can use `updateWith`, e.g.
```scala
namespaceTypeMap.updateWith(namespace, {
   case Some(existing) => Option(existing ++ typesInNamespace)
   case None => Option(typesInNamespace)
})
```
And do a similar thing below

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala [hunk 3]
```diff
@@ -22,7 +22,7 @@ class CallTests extends CSharpCode2CpgFixture {
 
       inside(writeLine.argument.l) {
         case (base: Identifier) :: (strArg: Literal) :: Nil =>
-//          base.typeFullName shouldBe "System.Console"
+          //          base.typeFullName shouldBe "System.Console"
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala:25]: Does this base have a type yet or not? If it does then we can uncomment it

**Review by DavidBakerEffendi — CHANGES_REQUESTED** [review]
Some minor style recommendations

File: joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala [hunk 4]
```diff
@@ -16,12 +16,23 @@ trait AstForExpressionsCreator(implicit withSchemaValidation: ValidationMode) {
...
+      case ObjectCreationExpression     => astForObjectCreationExpression(expr)
+      case SimpleMemberAccessExpression => astForSimpleMemberAccessExpression(expr)
+      case _: IdentifierNode            => astForIdentifier(expr) :: Nil
+      case _                            => notHandledYet(expr)
+  }
+
+  private def astForAwaitExpression(awaitExpr: DotNetNodeInfo): Seq[Ast] = {
+    /* fullName is the name in case of STATIC_DISPATCH */
+    val node =
+      callNode(awaitExpr, awaitExpr.code, "<operator>.await", "<operator>.await", DispatchTypes.STATIC_DISPATCH)
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/AstForExpressionsCreator.scala:33]: Could we assign `<operator>.await` to a constant in the C# `Defines`?

File: joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala [hunk 5]
```diff
@@ -10,7 +10,7 @@ import scala.collection.mutable
 
 class CSharpScope(typeMap: TypeMap) extends Scope[String, DeclarationNew, ScopeType] {
 
-  private val typesInScope = mutable.Set.empty[CSharpType]
+  private val typesInScope = mutable.Set.empty[CSharpType].addAll(typeMap.findGlobalTypes)
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala:13]: What are these global types? Since the effect here is that global types from other files are visible in this file, is that intended?

**Comment by DavidBakerEffendi** [comment]
@karan-batavia I see you're adding more features into this PR. Could you list all the issues this resolves in your description, please?

File: joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala (hunk 2 above)
Comment (karan-batavia) [reply joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/TypeMap.scala:110]: Yup, that's the method I could not find. Thanks.

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala (hunk 3 above)
Comment (karan-batavia) [reply joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/querying/ast/CallTests.scala:25]: This doesn't seem to be a test written by me, maybe `scalafmt` added this change.

File: joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala (hunk 5 above)
Comment (karan-batavia) [reply joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala:13]: Yes, classes without a parent namespace are added to the `global` namespace.

Comment (karan-batavia) [reply joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/datastructures/CSharpScope.scala:13]: The downstream changes for a global namespace still need to be handled. But for the scope of this PR, adding types which do not have a parent namespace should be good.

File: joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/Defines.scala [hunk 6]
```diff
@@ -0,0 +1,5 @@
+package io.joern.csharpsrc2cpg.astcreation
+
+object Defines {
+  val AwaitOperator = "<operator>.await"
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/csharpsrc2cpg/src/main/scala/io/joern/csharpsrc2cpg/astcreation/Defines.scala:4]: This should go under `io.joern.csharpsrc2cpg.CSharpOperators` (under `Constants.scala`)

**Review by DavidBakerEffendi — APPROVED** [review]
