### PR TITLE
[ruby] Alias and Method Lowering

### LINKED ISSUE #5116: [Bug] [ruby] Alias Expression in Unexpected Location
**Describe the bug**
The alias expressions are typically direct children of type declarations, however sometimes it's not...
```
2024-11-19 14:24:41.630 WARN AstCreator: Unhandled expression of type AliasStatement
2024-11-19 14:24:41.661 WARN AstCreator: Could not represent expression: alias orig_lock! lock! (AliasStatement) (config/initializers/active_record_lock_issue_3664.rb), skipping
```

**To Reproduce**
Parse `git@github.com:zammad/zammad.git`

### PR DESCRIPTION
**Pull request by AndreiDreyer**
* Moved `AliasStatement` lowering to `AstCreator`
* Added handling to ensure methods are lowered to directly under the respective `TYPE_DECL` when found in the `<body>` method.

Resolves #5116

### CODE REVIEW

File: joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala [hunk 1]
```diff
@@ -595,4 +603,15 @@ trait AstForFunctionsCreator(implicit withSchemaValidation: ValidationMode) { th
     if (accessModifierStack.nonEmpty) accessModifierStack.pop()
   }
 
+  private def shouldUseSurroundingTypeFullName: Boolean = {
+    val inBodyMethodScope = scope.surroundingScopeFullName.exists(x => x.split("[.]").takeRight(1).head == "<body>")
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala:607]:
```suggestion
    val inBodyMethodScope = scope.surroundingScopeFullName.exists(x => x.split("[.]").takeRight(1).contains(TypeDeclBody)
```

File: joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala [hunk 2]
```diff
@@ -595,4 +603,15 @@ trait AstForFunctionsCreator(implicit withSchemaValidation: ValidationMode) { th
...
+
+    scope.surroundingAstLabel match {
+      case Some(astLabel) =>
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/rubysrc2cpg/src/main/scala/io/joern/rubysrc2cpg/astcreation/AstForFunctionsCreator.scala:610]: Could look like 
```scala
scope.surroundingAstLabel match {
       case Some(NodeTypes.METHOD) => inBodyMethodScope
       case _ => false
 }
 ```

**Review by DavidBakerEffendi — APPROVED** [review]
Just two style-related suggestions
