### PR TITLE
[gosrc2cpg] - Go array index access call node handling

### LINKED ISSUE #3667: [GO] - Error while creating receiver node
```
java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:662) ~[scala-library-2.13.10.jar:?]
	at scala.collection.immutable.Nil$.head(List.scala:661) ~[scala-library-2.13.10.jar:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.processReceiverAst(AstForMethodCallExpressionCreator.scala:131) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.callMethodFullNameTypeFullNameAndSignature(AstForMethodCallExpressionCreator.scala:122) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.preReqForCallNode(AstForMethodCallExpressionCreator.scala:55) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.astForCallExpression(AstForMethodCallExpressionCreator.scala:16) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstForMethodCallExpressionCreator.astForCallExpression$(AstForMethodCallExpressionCreator.scala:12) ~[classes/:?]
	at io.joern.gosrc2cpg.astcreation.AstCreator.astForCallExpression(AstCreator.scala:19) ~[classes/:?]
```

### PR DESCRIPTION
**Pull request by pandurangpatil**
1. Refactored the existing implementation of the array IndexAccess call node.
2. Changed it to handle it recursively, creating those many index access call nodes.
3. Updated unit tests to cover more use cases.
4. Ignored IndexAccess unit tests for Map, as it will take more time to handle that scenario. It will be done in a separate PR.
5. Added file details in warning logs.
6. Review comment fixes from the PR #3666 
7. This PR should resolve #3667, #3648 and #3632

TODO: Handle indexAccess call node for `Map` type.

### CODE REVIEW

File: joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala [hunk 1]
```diff
@@ -75,11 +78,43 @@ trait AstForExpressionCreator(implicit withSchemaValidation: ValidationMode) { t
...
+      identifierAst.head.root.get.properties
+        .get(PropertyNames.TYPE_FULL_NAME)
+        .getOrElse(Defines.anyTypeName)
+        .toString
+        .stripPrefix("*")
+        .stripPrefix("[]")
+    (identifierAst, identifierTypeFullName)
+  }
+//
+//  private def extractBaseType(input: String): String = {
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala:101]: Remember to remove commented out code or attach a note if you still want to keep it

File: joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala [hunk 2]
```diff
@@ -54,8 +53,12 @@ trait AstForExpressionCreator(implicit withSchemaValidation: ValidationMode) { t
   }
 
   private def astForStarExpr(starExpr: ParserNodeInfo): Seq[Ast] = {
-    val cNode   = createCallNodeForOperator(starExpr, Operators.indirection)
     val operand = astForNode(starExpr.json(ParserKeys.X))
+    val typeFullName = operand.head.root.get.properties
```
Comment (DavidBakerEffendi) [inline joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala:57]: These `head.root.get` seem unsafe. See if something like this works:
```scala
operand.headOption
  .flatMap(_.root)
  .map(_.properties.get(PropertyNames.TYPE_FULL_NAME))
  .getOrElse(Defines.anyTypeName)
  .toString
```

**Review by DavidBakerEffendi — CHANGES_REQUESTED** [review]

File: joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala (hunk 2 above)
Comment (pandurangpatil) [reply joern-cli/frontends/gosrc2cpg/src/main/scala/io/joern/gosrc2cpg/astcreation/AstForExpressionCreator.scala]: done

**Review by DavidBakerEffendi — APPROVED** [review]
