### PR TITLE
[C#] Fix space in dependency name

### LINKED ISSUE #4420: [C#] Dependency download fails non malformed URL
**Describe the bug**
Depenendecy Downloader fails if URL has some spaces or incorrect characters: `java.net.URISyntaxException: Illegal character in path at index 37: https://www.nuget.org/api/v2/package/ System.Security.Cryptography.Pkcs/6.0.4` 

**To Reproduce**
1. Start a download dependency enabled scan with `csharpsrc2cpg`  on a repo which contains referenced package with a space in the XML
2. Dependency downloader builds the URL as `https://www.nuget.org/api/v2/package/ System.Security.Cryptography.Pkcs/6.0.4`
3. We get an exception

Example: 
```xml
  <ItemGroup>
    <PackageReference Include="System.ServiceModel.Primitives" Version="4.10.3" />
    <PackageReference Include=" System.Security.Cryptography.Pkcs" Version="6.0.4" />
  </ItemGroup>
```

**Expected behavior**
Spaces in URLs can be removed or if downlaod fails, skip existing download and move on

### PR DESCRIPTION
**Pull request by karan-batavia**
Resolves #4420

### CODE REVIEW

File: joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/DependencyTests.scala [hunk 1]
```diff
@@ -141,4 +141,28 @@ class DependencyTests extends CSharpCode2CpgFixture {
...
+    val config = Config().withDownloadDependencies(true);
+    "not throw a exception" in {
+      val cpg = code("""
+          |namespace Foo;
+          |""".stripMargin)
+        .moreCode(
+          """
+            |<Project Sdk="Microsoft.NET.Sdk">
+            |    <ItemGroup>
+            |      <PackageReference Include=" System.Security.Cryptography.Pkcs" Version="6.0.4"/>
```
Comment (AndreiDreyer) [inline joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/DependencyTests.scala:154]: Is it possible for the `Version` to also have leading or trailing spaces?

Comment (karan-batavia) [reply joern-cli/frontends/csharpsrc2cpg/src/test/scala/io/joern/csharpsrc2cpg/passes/DependencyTests.scala:154]: It's a bug we found on one repository, both of them shouldn't have spaces.

**Review by AndreiDreyer — APPROVED** [review]
